### ISSUE TITLE
Reading Mode Duplicates Notes -&- Numbered Notes Sort Incorrectly

### ISSUE THREAD

**Issue by ssumppg** [gasparschott/obsidian-continuous-mode#22]
Issue 1: Any notes that are in _Reading Mode_ while using _Continuous Mode_ will be preceded by an _Editing Mode_ duplicate of that note. 

Issue 2: Alphabetical sorting of notes in _Continuous Mode_ does not sort numbers properly. The displayed order in the left-side navigation pane is the order I wanted; "Untitled" was all the way at the end rather than at the beginning, and "Untitled 1" was directly followed by "Untitled 10" & "Untitled 11" rather than "Untitled 2".

<img width="768" alt="Screenshot 2024-07-14 192319" src="https://github.com/user-attachments/assets/7649d57e-f83b-4de2-94c1-914895a90ded">
<img width="872" alt="Screenshot 2024-07-14 192504" src="https://github.com/user-attachments/assets/a88d3ba8-8992-478b-88da-4acfad36158a">
<img width="872" alt="Screenshot 2024-07-14 192532" src="https://github.com/user-attachments/assets/24847e7d-dea5-412e-99e0-1e448c618cf5">
<img width="872" alt="Screenshot 2024-07-14 192614" src="https://github.com/user-attachments/assets/508711fd-883a-48a7-9934-58498b0a972f">
<img width="872" alt="Screenshot 2024-07-14 192729" src="https://github.com/user-attachments/assets/08d1ec2e-ba52-48e0-8cca-b196eb9e887d">

**Comment by gasparschott** [comment]
Thanks for the report. I believe issue #1 has been fixed in the latest version. Let me know if you're still having the problem.
I will look into the sorting issue.

**Comment by ssumppg** [comment]
Yep, looks like issue 1 is fixed. Thank you! :)

**Comment by gasparschott** [comment]
Sorting is fixed now, too. Thanks for pointing this out.

**Comment by ssumppg** [comment]
Of course! 

I checked out the sorting and it does look like, for the most part, it's fixed. But I did find a couple of edge cases where the documents still don't sort the same way they're displayed in the Obsidian hierarchy: 

<img width="873" alt="Screenshot 2024-07-25 100407" src="https://github.com/user-attachments/assets/4a24232b-f36d-4f3f-b15a-641d4c54d2d2">
<img width="873" alt="Screenshot 2024-07-25 100443" src="https://github.com/user-attachments/assets/5b71a0d9-32fc-4351-b72c-6b3808afdb5a">
<img width="873" alt="Screenshot 2024-07-25 100545" src="https://github.com/user-attachments/assets/e10146d6-c7fb-4ef0-b337-a23c1e428195">

As you can see, "Untitled" still appears at the end of the tab list rather than the beginning, and it appears that files with underscores after a number are placed ahead of files ending with that same number, even if there are more characters after the underscore.

I really appreciate you taking the time to fix all these! Thank you for your hard work. :)

**Comment by gasparschott** [comment]
You're very welcome! I very much appreciate your bug reports—it's impossible for one person to test all scenarios in an app as flexible as Obsidian, and I certainly want to make Continuous Mode as bug-free as it can be. Keep them coming—or rather, let's hope you won't need to!

All the sorting issues should now be fixed—really! The problems revolved around the "localeCompare" function options, which I had not set to "numeric", and using the full file name with the extension instead of the base name only as the sort string.
